"""
Django settings for ecourses project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Để thực thi một số thông tin qua trọng
SECRET_KEY = 'django-insecure-0(n#a4k6o+u2d_v$_p3l=53i_llz0&yz_j_2f!vcz3(7-a56!)'

# SECURITY WARNING: don't run with debug turned on in production!
# Debug là true để trong quá trình chạy có lỗi thì sẽ thông báo lên cho mình biết. Khi triển khai lên server thì tắt đi
DEBUG = True

# Các host được phép truy cập vào
ALLOWED_HOSTS = []


# Application definition
# Trong ứng dụng có rất nhiều cái app và phải đưa vào trong này thì django mới hiểu được
INSTALLED_APPS = [
    'django.contrib.admin',
    # 2 cái dưới này dùng để authen
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses.apps.CoursesConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework'
]

# Middleware là giữa các phần ta có thể xây dựng một cái middleware để chặn các request lại để kiểm tra, xử lý một công việc gì đó trước khi gửi vào bên trong server của mình
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecourses.urls'
# Template không dùng nữa vì mình sẽ dùng react
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecourses.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# sqlite là một tập tin và django tạo ra sẽ tương tác với sqlite nên mình phải cấu hình lại. Django có thể tương tác với nhiều CSDL cùng lúc nếu mình muốn
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecoursesdb',
        'USER': 'root',
        'PASSWORD': '23051998',
        'HOST': ''
    }
}

AUTH_USER_MODEL = 'courses.User'


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = 'static/'

# %s là nó sẽ trỏ đến BASE_DIR trỏ đến thẳng thư mục project của chúng ta
# course chính là tên project + tên foulder (static)
MEDIA_ROOT = '%s/courses/static' % BASE_DIR

# ckeditor path
CKEDITOR_UPLOAD_PATH = 'lessons/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
